apiVersion : apps/v1
kind: Deployment
metadata:
  name: nettodoapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nettodoapi
  template:
    metadata:
      labels:
        app: nettodoapi 
    spec:
      containers:
        - name: nettodoapi 
          image: smartidedemo.azurecr.io/nettodoapi
          ports:
          - containerPort: 80